### ISSUE TITLE
Проблема с win64 и Release версией в VS

### ISSUE THREAD

**Issue by ghost** [mrognor/Easy_Network#1]
Привет друг! Большое спасибо за проделанную работу! Возможно, я первый пользователь твоей библиотеки, и она мне очень нравится, но, к сожалению, у меня возникли некоторые проблемы при работе с ней. Изначально я думал, что все заработает из коробочки, но потом проснулся, и сделал следующее: установил последнюю версию VS, создал новый чистый проект и установил [EasyNetwork-v0.0.1-Windows-x86-64.zip](https://github.com/mrognor/Easy_Network/releases/download/v0.0.1/EasyNetwork-v0.0.1-Windows-x86-64.zip)
 как ты описал на хабре. Создал файл main.cpp и скопировал туда весь код из [TCP_FileSender_Server.cpp](https://github.com/mrognor/Easy_Network/blob/master/Examples/TCP_FileSender_Server.cpp), изменив лишь #include "../EN_TCP_Server.h" на #include "EN_TCP_Server.h", иначе файл не определялся.
1) В таком виде код компилируется только в версии Debug/x86, если же пытаться скомпилировать его в Debug/x64, 
то не проходит проверка на 32бит систему и компилятор ищет файлы из линукса 
![image](https://user-images.githubusercontent.com/105318277/185611859-2cced2bd-8666-409d-830e-6ecf6aade2e0.png)
![image](https://user-images.githubusercontent.com/105318277/185611949-e2a46c92-cc34-4133-84b0-4532b3d85314.png)
2)Хорошо, допустим пока будем все компилировать в Debug/x86, но если попытаться скомпилировать этот же файл в релиз версии Release/x86, то появляются следующие ошибки: 
![image](https://user-images.githubusercontent.com/105318277/185612392-02f1dde4-29a6-4c46-8ef5-cc16cdb858e1.png)
Запустить же версию Debug/x86 на другом компьютере мне не удавалось.
Возможно я что-то делаю не правильно, поэтому оно не хочет работать((
Очень жду помощи, заранее Спасибо!

**Comment by mrognor** [comment]
Привет! Прости что долго не отвечал. Сегодня посмотрю как можно решить проблемы.

**Comment by mrognor** [comment]
Поправил все. Теперь в релизе есть отдельные архивы для x86 и x64 windows. Внутри них лежат debug и release версии библиотеки. В Visual Studio надо поменять дополнительные зависимости в вводе линковщика. Выбрать для каждой конфигурации свой файл с библиотекой. Для запуска debug версий программ может не хватать dll файлов. Для устранения проблем можно положить в архив с бинарником все нужные файлы. Чтобы узнать эти файлы можно запустить программ и посмотреть на ошибки.
